- id: doi:10.1038/s41596-023-00950-4
  description: A protocol for multi-omics integration with user-friendly web-based tools that enable researchers to efficiently integrate different data types for scientific discovery.
  image: https://www.omicsanalyst.ca/resources/gallery/network9.png
  buttons:
    - type: website
      text: OmicsAnalyst
      link: https://www.omicsanalyst.ca/
    - type: website
      text: OmicsNet
      link: https://www.omicsnet.ca/

- id: doi:10.1002/etc.5954
  image: https://setac.onlinelibrary.wiley.com/cms/asset/ef8a1122-ca4d-48da-b538-2847f3d99268/etc5954-fig-0002-m.jpg

- id: doi:10.1038/s41467-024-50613-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-024-50613-5/MediaObjects/41467_2024_50613_Fig2_HTML.png
