site_name: Ewald Lab Handbook
site_author: Jessica Ewald
use_directory_urls: true
site_description: >-
  Collection of protocols, blog posts, and random advice on scientific research. 

theme:
  name: material
  palette:
    primary: custom
  font:
    text: Noto
  logo: assets/icon.png
  favicon: assets/favicon.png


extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://ewaldlab.org


# Page tree
nav:
  - Home: index.md
  #- Reading List:
    #- Overview: reading/reading-overview.md
    #- 1. Tox21: reading/1-tox21.md
    #- 2. Image-based profiling: reading/2-image-based-profiling.md
    #- 3. Cell profiling for tox: reading/3-profiling-tox.md
  - Useful courses: courses-overview.md
  - Joining the lab: join-lab.md
  - Onboarding: onboarding.md
