name: build-site
run-name: build live site

on:
  workflow_call:
  workflow_dispatch:

env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: self-hosted

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          sudo ~/.ruby-build/install.sh

      - name: Install Ruby
        run: |
          ruby-build 3.2.3 /opt/hostedtoolcache/Ruby/3.2.3/x64
          mkdir -p /opt/hostedtoolcache/Ruby/3.2.3/x64
          touch /opt/hostedtoolcache/Ruby/3.2.3/x64.complete

      - name: Add Ruby to PATH
        run: echo "/opt/hostedtoolcache/Ruby/3.2.3/x64/bin" >> $GITHUB_PATH

      - name: Install Ruby packages
        uses: ruby/setup-ruby@v1.172.0
        with:
          ruby-version: "3.2.3"
          bundler-cache: true

      - name: Get Pages URL
        id: pages
        uses: actions/configure-pages@v4

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set root URL
        run: |
          printf "\n\nurl: ${{ steps.pages.outputs.origin }}" >> _config.yaml

      - name: Build live version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"

      - name: Commit live site to Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
          clean-exclude: ${{ env.PREVIEWS_FOLDER }}
          force: false
